version: "3.7"

services:
  telegram_server:
    container_name: "telegram_server"
    restart: "no"
    env_file:
      - ./server/configs/.env
    build:
      context: ./server
    environment:
      - TZ=Asia/Bishkek
      - NODE_ENV=production
      - PORT=4000
      - HOST=0.0.0.0
    ports:
      - 4000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./server:/src
      - /src/node_modules
    command: yarn start
  telegram_nginx:
    image: nginx
    restart: "no"
    container_name: "telegram_nginx"
    ports:
      - 80:80
    depends_on:
      - telegram_server
    links:
      - telegram_server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/telegram-available:/etc/nginx/telegram-available
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client/dist:/dist
