version: "3.7"

services:
  telegram_client:
    container_name: "telegram_client"
    restart: "no"
    build:
      context: ./client
    environment:
      - TZ=Asia/Bishkek
      - NODE_ENV=development
      - PORT=8080
      - HOST=0.0.0.0
      - API_HOST=http://telegram_api:4000/api
    ports:
      - 8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./client:/src
      - ./client/dist:/src/dist
      - /src/node_modules
    command: yarn serve
  telegram_server:
    container_name: "telegram_server"
    restart: "no"
    env_file:
    - dev.env
    build:
      context: ./server
    environment:
      - TZ=Asia/Bishkek
      - NODE_ENV=development
      - PORT=4000
      - HOST=0.0.0.0
    ports:
      - 4000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./server:/src
      - /src/node_modules
    command: yarn dev
  telegram_nginx:
    image: nginx
    restart: "no"
    container_name: "telegram_nginx"
    ports:
      - 80:80
    depends_on:
      - telegram_server
      - telegram_client
    links:
      - telegram_server
      - telegram_client
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/telegram-available-local:/etc/nginx/telegram-available
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
